MENTORING-T-68 Lotto프로그램 #1.0 - 선택사항 3번 선택
BI-kotlin-in-action/DaeyeonKim-Project-Hw pull request #1
Opened 2023-11-06 18:01 UTC by kim946509

로또 과제 코드입니다.
선택 사항 중 3번을 선택하여 작성해 보았습니다. 감사합니다! 

선택 사항 3 : 각 코드의 역할과 도메인에 따라 파일 혹은 패키지를 분리해 본다.

2023-11-07 12:03 UTC, konempty commented
앗 ㅋㅋㅋ 커밋 하나에 모든 변경사항을 몰아두는건 좋지 않습니다!
그리고 다음부터는 커밋 메시지만 읽고 변경사항을 예측할수 있도록 명시적으로 적어주세요!

2023-11-07 12:33 UTC, konempty requested changes
크 기본 구현내용은 충실히 구현하셨군요
너무 좋습니다~!
조금만더 수정 부탁드릴게요!

2023-11-07 12:33 UTC, konempty commented on Lotto/.gitignore
> +Lotto.iml
<img width="302" alt="스크린샷 2023-11-07 오후 9 04 50" src="https://github.com/BI-kotlin-in-action/DaeyeonKim-Project-Hw/assets/44064530/101dd03e-8288-47bd-ad30-9fab756fc442">


파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-11-07 12:33 UTC, konempty commented on Lotto/.gitignore
> +Lotto.iml
그리고 .idea 폴더도 깃 이그노어 처리 해주시면 좋을것 같아요!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +    val winnigsRule = mapOf(1 to 100000, 2 to 5000, 3 to 100, 4 to 5)
오호 맵으로 처리하는것도 좋았지만 이럴때 유용한건 enum입니다!
enum을 한번 사용해보세요

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            winNumber.add(num)
중복 없이 숫자를 뽑는 로직은 셔플링과 subList를 사용하는거예요!
ex)
1, 2, 3, 4, 5, 6의 숫자 배열에서 중복없이 3개를 뽑으려면
셔플링 후(2, 6, 3, 4, 5, 1)
앞에서 부터 3개 추출 (2, 6, 3)

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            if (winNumber.contains(lotto.lottoNumber.elementAt(i))) {
```kotlin
val count = lotto.lottoNumber.count{ number -> winNumber.contains(number) }
```
요렇게 한줄로 처리할것 같구요
더 나아 가면 코틀린에서는 intersect라는 교집합을 구하는 메소드가 이미 존재 하기 때문데
```kotlin
val count = winNumber.intersect(lotto.lottoNumber)
```
요렇게 처리 할것 같아요!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            3 -> rank[4]++
enum을 사용하면 요 코드도 더 효율적으로 처리할수 있을것 같은데 고민해보시면 좋을것 같습니다~!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            winnigs += rank[i] * (winnigsRule[i] ?: 0)
요기도 enum을 활용했을때 좀더 효율적으로 바꿔보세요

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Lotto.kt
> +class Lotto(val lottoNumber: Set<Int> = sortedSetOf(6)) {
로또를 일급컬렉션화 한건 정말 좋구요
좀더 나아가면 lottos: MutableList<Lotto> 도 일급 컬렉션화 가능하지 않을까요??

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +        println("총 당첨금 : ${winnigs}KW")
유저의 입력을 받고 결과를 화면에 출력하는 코드들 또한 주로 view라는 이름의 도메인으로 분리하는걸 추천합니다!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Main.kt
> +    host.setWinNumber()
으흠 요긴 코드가 꽤 어지럽네요 ㅠㅠ
요 프로젝트에서 나눌만한 3가지 패키지을 알려드릴게요!
1. 도메인 : 단순히 정보를 가지고 패키지 간의 정보 전달을 위해 사용되는 클래스 모음
2. 뷰 : IO에 관련된 모든 로직을 수행하는 클래스 모음
3. 컨트롤러 : 뷰와 도메인을 받아들여 프로그램의 전체과정을 컨트롤하는 역할

요렇게 나눈다면 host는 컨트롤러라 하기엔 호스트가 가지지 못한 역할이 너무 많고 
그렇다고 도메인이 되기에는 너무 많은 비지니스 로직을 가지고 있네요 ㅠㅠ

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +    var lottoList = mutableListOf<Lotto>()
lottoList는 불변형이여도 좋을것 같은데 var로 선언하신 이유가 있을까요??

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Lotto.kt
> +        const val price: Int = 1000
제가 코틀린 인 액션에서 말씀드린대로 요렇게 하면 java의 static에 대응하지 못하고 
object를 생성해서 관리되기 때문에 효율적이지 못해요 ㅠㅠ
\@JvmStatic을 붙혀주셔야 하구요
상수의 이름은 대문자로 이루어 지는게 개발자들 사이의 암묵적인 룰입니다!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +                if (numArray.contains(num)) continue
참고로 sortedSet을 쓴다면 contains를 포함하지 않아도
add를 할때 자동으로 중복을 처내기 때문에 저희가 다시 검사할 이유는 없습니다~!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +        }
요기서는 
```kotlin
        lottoList.forEachIndexed { index, lotto ->
            println("${index + 1} : " + lotto.lottoNumber.joinToString(" "))
        }
```

요렇게 코틀린의 문법을 최대한 이용하는게 코틀린스러운 코드입니다~!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +    val winNumber = sortedSetOf<Int>()
winNumber도 Lotto클래스로 재활용할수도 잇을것 같구요
별도의 도메인 클래스로 분리한다고 해도 좋을것 같아요!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            val num = (Math.random() * 45 + 1).toInt()
코틀린에서는 Math 대신 아래와 같이 Random을 쓰는게 더 직관적입니다~!
```kotlin
        Random.nextInt(1..45)
```

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +        val directlyBuy = readln().toInt()
자동 구매가 autoBuy라면 수동 구매는 manualBuy가 어울릴것 같아요~!

2023-11-07 12:33 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +            val numArray = sortedSetOf<Int>()
이름을 통일 시켰으면 좋을것 같은데
같은 역할을 수행하는 변수가 어디선 lottoNumber라고 부르고 어디서는 numArray라고 부르면 헷갈릴것 같아요!

2023-11-08 08:39 UTC, kim946509 commented on Lotto/.gitignore
> +Lotto.iml
넵! 감사합니다. 수정하겠습니다.

2023-11-08 09:05 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            winNumber.add(num)
넵! 뭔가 다른 방법 있지 않을까 했었는데 그런 방법이 있네요 ㅎㅎ 수정 해 보겠습니다!

2023-11-08 09:06 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            if (winNumber.contains(lotto.lottoNumber.elementAt(i))) {
넵! 정말 간결해지네요.. 수정하겠습니다!

2023-11-08 09:07 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            3 -> rank[4]++
넵. enum class 사용해서 한번 수정해 보겠습니다!

2023-11-08 09:10 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +        }
넵 최대한 코틀린 문법 활용하겠습니다!

2023-11-08 09:29 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            val num = (Math.random() * 45 + 1).toInt()
넵 훨씬 직관적이네요. 감사합니다!

2023-11-08 09:31 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +        val directlyBuy = readln().toInt()
넵! 감사합니다!

2023-11-08 09:32 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +    val winNumber = sortedSetOf<Int>()
넵! 일단 Lotto클래스 재활용해서 작성해 보겠습니다!

2023-11-08 09:38 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +            val numArray = sortedSetOf<Int>()
넵! 바로 위에 수동으로 구매할 때도 lottoNumber인데 numArray이라고 하면 헷갈릴 것 같네요. 같은 역할을 하는 변수는 같은 이름으로 통일 시키겠습니다! 코멘트 감사합니다.

2023-11-08 10:12 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            winnigs += rank[i] * (winnigsRule[i] ?: 0)
넵! 동일하게 수정해보겠습니다.

2023-11-08 10:12 UTC, kim946509 commented on Lotto/src/main/kotlin/Lotto.kt
> +class Lotto(val lottoNumber: Set<Int> = sortedSetOf(6)) {
넵! 일급 컬렉션으로 만들어서 코드 수정하겠습니다!

2023-11-08 10:27 UTC, kim946509 commented on Lotto/src/main/kotlin/Lotto.kt
> +        const val price: Int = 1000
넵 ㅠㅠ 그렇다면 혹시 이럴 때 좋은 대안 알려주실 수 있을까요? 제가 생각한 방법은 Lotto의 매개변수로 정의해주거나 main함수에서 정의를 해주는 것이 생각나는데 것 같은데 둘 다 그렇게 좋은 방법은 아닌 것 같아서요.

2023-11-08 10:29 UTC, kim946509 commented on Lotto/src/main/kotlin/Main.kt
> +    host.setWinNumber()
그렇다면 혹시 host설계를 잘못한 것일까요..? 그렇다면 host를 다시 설계 해야 할까요?

2023-11-08 11:19 UTC, konempty requested changes
코드가 많이 좋아졌네요 ㅋㅋㅋ 조금만더 수정 부탁드릴게요!

2023-11-08 11:19 UTC, konempty commented on Lotto/.idea/.gitignore
> +/dataSources.local.xml
아하.. .idea 추가하고 요 파일들은 올라오지 않도록 해주셔야 해요...!
https://devjeonblog.oopy.io/3d13207f-b830-4bbc-9d35-bd6dbfc824f0

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +}
요 enum은 Host랑 큰 관련이 없어보이는데 별도의 파일로 빼내는게 좋을것 같아요!

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +            else -> WinningsCal.LOSE.count++ // 낙첨
아핫.. enum이 상태를 가지는건 별로 좋지 않아요
Map<WinningsCal, Int>형태의 맵으로 개수를 저장하는걸 추천드릴게요~!

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +        val selectNumber = (1..45).toMutableList() //
ㅋㅋㅋ 주석 처리를 하다가 말았군요

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +        val selectNumber = (1..45).toMutableList() //
selectNumber 는 프로그램 전역적으로 유니크해도 좋을것 같은데
static하게 선언하는게 어떨까요??

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +        selectNumber.shuffle()
https://velog.io/@liketaehoon/kotlin-shuffle-vs-shuffled
shuffle과 shuffled를 잘 구분해서 쓰면
selectNumber를 immutable한 리스트로도 선언할수 있게돼요!

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Lotto.kt
> +        val price = 1000
참고로 \@JvmStatic을 붙혀도 되구요 const val로 선언해도 자바의 static한 효과를 낼수 있어요!

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Main.kt
> +    host.setWinNumber()
네네 조금 변경이 필요할것 같아요!

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Main.kt
> +    val view = View()
이렇게 한다면 컨트롤러의 역할은 어떤 클래스가 수행하게 되는걸까요??

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +        val directlyBuy = readln().toInt()
요거 수정 빠트리신것 같네요 ㅎㅎ

2023-11-08 11:19 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +                val num = (Math.random() * 45 + 1).toInt()
여기도 Random.nextInt(1..45)를 쓰는게 좋을것 같아요!

2023-11-08 16:17 UTC, kim946509 commented on Lotto/.idea/.gitignore
> +/dataSources.local.xml
넵 참고해서 수정하겠습니다!

2023-11-08 16:17 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +}
넵 밖으로 따로 만들겠습니다.

2023-11-08 16:18 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +            else -> WinningsCal.LOSE.count++ // 낙첨
넵!! enum에서 count 없에고 Map으로 수정하겠습니다.

2023-11-08 16:21 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +        selectNumber.shuffle()
넵 구분해서 사용해 보겠습니다!

2023-11-08 16:26 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +        val selectNumber = (1..45).toMutableList() //
selectNumber를 함수화 시켜보았습니다. 이러한 방향으로 수정하는게 맞을까요?

2023-11-08 16:26 UTC, kim946509 commented on Lotto/src/main/kotlin/Lotto.kt
> +        val price = 1000
넵!! 감사합니다!

2023-11-08 16:28 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +        val directlyBuy = readln().toInt()
아 넵! 죄송합니다. 수정하였습니다

2023-11-08 16:30 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +                val num = (Math.random() * 45 + 1).toInt()
넵!!  감사합니다.

2023-11-08 16:47 UTC, kim946509 commented on Lotto/src/main/kotlin/Main.kt
> +    val view = View()
따로 Controller을 만들어서 수정하도록 하겠습니다!

2023-11-09 02:28 UTC, konempty requested changes
크 코드가 많이 깔끔해졌네요 👍 👍 
조금만 더 수정 부탁드릴게요!

2023-11-09 02:28 UTC, konempty commented on Lotto/.idea/inspectionProfiles/Project_Default.xml
> +</component>
.idea 폴더 내용들이 아직 남아 있네요 ㅠㅠ
깃이그노어 처리하고 이미 올라간 파일들을 지워주는 작업까지 해야 하는데 아래 링크를 참고해주세요
https://devjeonblog.oopy.io/3d13207f-b830-4bbc-9d35-bd6dbfc824f0

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/Controller.kt
> +class Controller {
무슨 컨트롤러인지 클래스 명만 보고 알수 있도록 지어주세요!
지금은 로또 프로그램이니까 로또 컨트롤러라는 느낌이 들도록 지으면 좋을것 같네요 ㅋㅋㅋ

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/Controller.kt
> +        val money = readln().toInt()
사용자의 입력을 받아들이는것 또한 뷰의 역할입니다!

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/Controller.kt
> +        View().printLotto(person.lottos) // Person이 Lottos를 출력하도록 명령
View의 메소드를 사용할때 마다 객체를 생성했다가 바로 버려지네요 ㅠㅠ
객체를 재활용하거나 혹시 객체가 불필요 하다면 static 메소드로 처리해주세요!

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +                totalRank[Rank.FIRST]?.plus(1) ?: 0 // totalRank[Rank.FIRST] = totalRank[Rank.FIRST] + 1
앗 ㅋㅋㅋㅋ...
null이 문제가 되니까 코드가 길어진것 같은데
totalRank.getValue(Rank.FIRST)
요렇게 하면 null이슈 없이 처리가 가능합니다!

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +                totalRank[Rank.FIRST]?.plus(1) ?: 0 // totalRank[Rank.FIRST] = totalRank[Rank.FIRST] + 1
그리고 count를 넣었을때 적절한 Enum값을 반환해주는건 Rank의 책임/역할 일것 같아요!
totalRank.getValue(Rank.getRank(count))
요런 느낌으로 가능하도록 수정 부탁드릴게요!

2023-11-09 02:28 UTC, konempty commented on Lotto/src/main/kotlin/SelectNumber.kt
> +    val selectNumber = (1..45).toMutableList()
1~45까지의 숫자 리스트는 프로그램 전역적으로 유니크 해도 괜찮을것 같은데
static하게 처리하는건 어떨까요??

2023-11-09 09:27 UTC, kim946509 commented on Lotto/.idea/inspectionProfiles/Project_Default.xml
> +</component>
아 넵.. 설정했었는데 다른 작업하다가 잘못됐네요.. 캐시 삭제까지 하고 제대로 올라가지 않는지 다시 확인해보겠습니다.
감사합니다!

2023-11-09 09:35 UTC, kim946509 commented on Lotto/src/main/kotlin/Controller.kt
> +        View().printLotto(person.lottos) // Person이 Lottos를 출력하도록 명령
네! 굳이 객체가 불필요 하여 static 메소드로 처리하겠습니다.

2023-11-09 09:35 UTC, kim946509 commented on Lotto/src/main/kotlin/Controller.kt
> +        val money = readln().toInt()
넵View쪽에서 처리하도록 수정하겠습니다.

2023-11-09 10:15 UTC, kim946509 commented on Lotto/src/main/kotlin/SelectNumber.kt
> +    val selectNumber = (1..45).toMutableList()
넵! static하게 처리하겠습니다.

2023-11-09 10:17 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +                totalRank[Rank.FIRST]?.plus(1) ?: 0 // totalRank[Rank.FIRST] = totalRank[Rank.FIRST] + 1
넵! null이 계속 문제가 되어서 코드가 지저분해지더라고요...감사합니다! 수정하겠습니다.

2023-11-09 10:38 UTC, konempty requested changes
거의 다온것 같아요!!
진짜 조금만더 수정 부탁드릴게요~!

2023-11-09 10:38 UTC, konempty commented on Lotto/src/main/kotlin/Lottos.kt
> +class Lottos(val list: MutableList<Lotto> = mutableListOf())
사실 제대로된 일급 컬렉션을 만드려면 컬렉션을 private로 숨기고 외부에서 직접 접근하는걸 차단 해야 해요..!

2023-11-09 10:38 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +    fun buyLotto() {
아하.. 요 메소드는 너무 하는 일이 많은것 같아요
그리고 패키지 분리가 필요할것 같은데

요 프로젝트에서 나눌만한 3가지 패키지을 알려드릴게요!

도메인 : 단순히 정보를 가지고 패키지 간의 정보 전달을 위해 사용되는 클래스 모음
뷰 : IO에 관련된 모든 로직을 수행하는 클래스 모음
컨트롤러 : 뷰와 도메인을 받아들여 프로그램의 전체과정을 컨트롤하는 역할

그런데 Person은 도메인이자, 뷰이자, 컨트롤러 같아 보여요 ㅠㅠ

2023-11-09 10:38 UTC, konempty commented on Lotto/src/main/kotlin/Rank.kt
> +        else -> Rank.LOSE
만약 Rank가 몇개의 번호를 맞춰야 하는지 알고 있다면 코드를 줄일수 있을것 같아요!

```kotlin

enum class Rank(val money: Int, val matchCount: Int) {
    FIRST(100000, 6),
    SECOND(5000, 5),
... 중략

fun getRank(count: Int): Rank = Rank.values().find{it.matchCount == count} ?: Lose
```

2023-11-09 10:38 UTC, konempty commented on Lotto/src/main/kotlin/Rank.kt
> +fun getRank(count: Int): Rank {
전역 함수화는 되도록이면 쓰지 않는걸 추천해드려요..!
그러고 보니 주석에는 동반객체로 선언한다고 잘 쓰신것 같은데 그렇게 안하신 이유가 뭘까요??

2023-11-09 10:38 UTC, konempty commented on Lotto/src/main/kotlin/SelectNumber.kt
> +}
요 함수랑 selectNumber도 어딘가에 속하도록 만들어 주세요
그게 패키지 분리거든요!

2023-11-09 10:58 UTC, kim946509 commented on Lotto/src/main/kotlin/Lottos.kt
> +class Lottos(val list: MutableList<Lotto> = mutableListOf())
넵! 감사합니다. 수정하겠습니다.

2023-11-09 11:29 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +    fun buyLotto() {
넵 Person의 역할을 줄이고 패키지를 분리하겠습니다. 감사합니다!

2023-11-09 11:33 UTC, kim946509 commented on Lotto/src/main/kotlin/Rank.kt
> +fun getRank(count: Int): Rank {
아 companion object사용은 지양한다고 이해해서 사용하지 않았었습니다ㅠ. 수정하겠습니다. 감사합니다

2023-11-09 11:36 UTC, kim946509 commented on Lotto/src/main/kotlin/Rank.kt
> +        else -> Rank.LOSE
넵! 감사합니다. 수정하겠습니다.

2023-11-09 11:37 UTC, kim946509 commented on Lotto/src/main/kotlin/SelectNumber.kt
> +}
넵! 가장 적합한 곳이 person과 lotto중에 고민했는데 lotto인것 같아 Lotto클래스에 속하도록 작성해 보겠습니다. 감사합니다!

2023-11-09 11:44 UTC, kim946509 commented on Lotto/src/main/kotlin/SelectNumber.kt
> +}
다시 생각해보니 컨트롤러가 적합해 보이기도 하네요..

2023-11-09 11:52 UTC, konempty requested changes
찐막 조금만 더 수정 부탁드릴게요~!

2023-11-09 11:52 UTC, konempty commented on Lotto/src/main/kotlin/Lotto.kt
> +        val selectNumber = (1..45).toMutableList()
mutableList가 아니더라도 가능한 shuffle을 쓸수 있는 방법을 찾아보시면 
그냥 (1..45)로도 가능할것 같아요!

2023-11-09 11:52 UTC, konempty commented on Lotto/src/main/kotlin/LottoBuyView.kt
> +fun manualBuyLotto(): Set<Int> {
전역 함수는 객체지향 관점에서 별로 좋은 방식이 아니예요 ㅠㅠ
특정 패키지, 클래스에 속하도록 수정해주세요

2023-11-09 11:52 UTC, konempty commented on Lotto/src/main/kotlin/Host.kt
> +    val totalRank = mutableMapOf(
요 결과는 Lottos의 결과이거나 Person의 결과가 아닐까요??

2023-11-09 11:52 UTC, konempty commented on Lotto/src/main/kotlin/Person.kt
> +    fun lottoBuy(lottoNumber: Set<Int>) {
수정요청까진 아니구요 쪼금 아쉬운데
로또 번호를 받아서 로또를 생성하는 역할을 Person이 수행하는건 너무 역할을 많이 준것 같아요
외부의 다른 도메인이 생성한 로또를 받아서 lottos에 넣는 방식이면 더 좋았을것 같아요~!

2023-11-09 11:55 UTC, kim946509 commented on Lotto/src/main/kotlin/Lotto.kt
> +        val selectNumber = (1..45).toMutableList()
넵 shuffle함수 관련해서 찾아보겠습니다! 감사합니다.

2023-11-09 12:03 UTC, kim946509 commented on Lotto/src/main/kotlin/LottoBuyView.kt
> +fun manualBuyLotto(): Set<Int> {
넵! ㅠ 특정 패키지에 속하도록 수정하겠습니다. 감사합니다!

2023-11-09 12:14 UTC, kim946509 commented on Lotto/src/main/kotlin/Host.kt
> +    val totalRank = mutableMapOf(
넵! person의 결과인 것 같네요ㅠ. person에 winnigs와 totalRank를 추가하겠습니다. 감사합니다!

2023-11-09 12:19 UTC, kim946509 commented on Lotto/src/main/kotlin/Person.kt
> +    fun lottoBuy(lottoNumber: Set<Int>) {
앗 넵! 다른 도메인을 만들거나 역할을 부여할 수 있는 도메인을 고려해 보겠습니다. 감사합니다!

2023-11-09 12:28 UTC, konempty approved these changes
찐막이라고 했으니 약속은 지켜야죠 ㅋㅋㅋ
너무 고생 많이하셨습니다 👍 👍 
이제 머지하셔도 좋습니다~!

2023-11-09 12:31 UTC, kim946509 commented
제가 많이 부족해서 답답하시고 코멘트 하실 부분이 많으셨을텐데 정말 감사합니다 :)

2023-11-09 12:31 UTC, merged